theme: dinky
title: BlobyAude
author: GitHub User audetri
email: triccaa@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 my first blog developed on GitHub

# social links
instagram_username : aatriccaa
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  audetri # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
